version: "3.8"

services:
  app:
    image: ${APP_IMAGE_TAG}
    volumes:
      - ./db:/db
      - ./certs:/certs
    environment:
      - ENV_FILE=/src/env/prod.env
      - APP_PORT=$APP_PORT
    command:
      - "uvicorn"
      - "main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "${APP_PORT}"
      - "--ssl-keyfile"
      - "../certs/private.pem"
      - "--ssl-certfile"
      - "../certs/public.pem"
    ports:
      - "${APP_PORT}:${APP_PORT}"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
